config/routes.rb
Rails.application.routes.draw do
  resources :subscription

  devise_for :admins
   root 'home#index'

   resources :pitch  do
    collection do 
      get 'success'
    end
  end

  resources :home

  resources :dashboard do
    collection do 
      get 'pitched'
      get 'pending'
      get 'all'
    end
  end

  resources :post

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/pitch.rb
class Pitch < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base

		validates :url,presence:true
	  validates :image,presence:true
	   validates :post,presence:true
	   validates :title,presence:true
	   validates :category,presence:true
	   validates :url, uniqueness: {message: "already exist"},if: "url.present?" 
	   
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	validates :email,presence:true
	validates :email, uniqueness: {message: "already subscribed to list, Spitch Newsletter."},if: "email.present?" 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :successful, :mailer



    def after_sign_in_path_for(resource_or_scope)
     if resource_name == :admin
         dashboard_index_path

  	end
  end


  def after_sign_up_path_for(resource_or_scope)
     if resource_name == :admin
  	   dashboard_index_path
      
     end
  end


  def after_sign_out_path_for(resource_or_scope)
     if resource_name == :admin
       new_admin_session_path
  end 

end

  def after_accept_path_for(resource)
  	accept_admin_invitation_path
  end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

def index
	if params[:search]
      @all_pitches = Pitch.all.where("company_name LIKE '%#{params[:search]}%' ") 
    else
    @all_pitches=Pitch.all.where("pitch_status='pending'").order("updated_at DESC")

    end		
end

def pending
	if params[:search]
      @all_pitches = Pitch.all.where("company_name LIKE '%#{params[:search]}%' ") 
    else
    @all_pitches=Pitch.all.where("pitch_status='pending'").order("updated_at DESC")

    end		
end

def all
	if params[:search]
      @all_pitches = Pitch.all.where("company_name LIKE '%#{params[:search]}%' ") 
    else
    @all_pitches=Pitch.all.order("updated_at DESC")

    end		
end

def pitched
	if params[:search]
      @all_pitches = Pitch.all.where("company_name LIKE '%#{params[:search]}%' ") 
    else
    @all_pitches=Pitch.all.where("pitch_status='pitched'").order("updated_at DESC")

    end		
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

		if params[:search]
		@posts = pagination.where("post LIKE '%#{params[:search]}%' or url LIKE '%#{params[:search]}%' or title LIKE '%#{params[:search]}%' or category LIKE '%#{params[:search]}%' ")   
		else
		@posts = pagination   
		end

	end

	def pagination

		@pagination=Post.order("id DESC").paginate(:page => params[:page], :per_page => 4)

	end
end

app/controllers/pitch_controller.rb
class PitchController < ApplicationController


def create
  @pitch = Pitch.create(pitch_params)
	@pitch.pitch_status="pending"
  @pitch.save

	redirect_to success_pitch_index_path

	session[:pitched]="true"

end


def edit
	@pitch=Pitch.find(params[:id])

end


def success

if !session[:pitched]
	redirect_to root_path
else
	session.delete(:pitched)
end

end

 def update
 	@pitch=Pitch.find(params[:id])
 	 	@pitch.update(pitch_params)
    if @pitch.pitch_status=="pending"
 	      redirect_to pending_dashboard_index_path
    elsif @pitch.pitch_status=="pitched"
        redirect_to pitched_dashboard_index_path
    end
  
 	  flash[:success]="Update for #{@pitch.company_name}, was successful"
 end

 def destroy
 	@pitch=Pitch.find(params[:id])
 	@pitch.destroy
 	redirect_to pitched_dashboard_index_path
 end
 
private
def pitch_params
params.require(:pitch).permit(:owner_name,:owner_email,:other_info,:launch_date,:category,:team_members,:company_address,:contact,:headline,:company_name,:app_link,:description,:pitch_status)
end


end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
  end

  def new
    @post=Post.new 
  end

  def edit
    @post=Post.find(params[:id]) 
  end


  def show
    @post=Post.find_by_url(params[:id]) 
  end

  def destroy
    
  end

 def update
  @post=Post.find(params[:id])
  if @post.update(post_params)
    if params[:send_email]=="yes"
      NewsletterMailer.newsletter(@post).deliver_now
      end
    redirect_to post_path(@post.url)
  else
    render 'edit'
  end
end

  def create
    @post = Post.new(post_params)
   
    if @post.save 
      if params[:send_email]=="yes"
      NewsletterMailer.newsletter(@post).deliver_now
      end
      redirect_to root_path 
    else
      render 'new'
    end
  end

    def destroy
  @post=Post.find(params[:id])
  @post.destroy
  redirect_to root_path
  end





  private
  def post_params
    params.require(:post).permit(:url, :image,:post,:title,:category)
  end
end

app/controllers/subscription_controller.rb
class SubscriptionController < ApplicationController
  	def create
	@subscription=Subscription.new(subscribe_params)
	@subscription.save

	end

	private 
	def subscribe_params
		params.require(:subscription).permit(:email)

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pitch_helper.rb
module PitchHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/views/admins/index.html.erb
<div class="container">
<nav  class="navbar navbar-inverse" role="navigation">
  
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">        
        <%= image_tag('GOFIX.png', class:'img-responsive', width:'400', height:'300')%>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "HOME" , home_index_path%></li>
      <li><%= link_to "ADD ADMIN", new_admin_invitation_path  %></li>
      <li>
      <li><%= link_to "FEEDBACKS", feedback_admins_path %></li>
      <li><%= form_tag url:{controller: 'admins', action:'index'}, method: :get , remote:true do %>
            <p>
              <%= text_field_tag :search %>
              <%= submit_tag "Search" %>
            </p>
        <%end%>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to  destroy_admin_session_path do %>
              <span class="glyphicon glyphicon-log-out"></span>
               Logout(<%= current_admin.email%>)
          <%end%>
      </li>
    </ul>
    </div>
</nav>
<div class="row">
<div class="custom-widgets">
   <div class="row-one">
    <div class="col-sm-6 col-md-4 col-lg-3 ">
      
      <div class="stats-left ">
        <h5>Total</h5>
        <h5> Users</h5>
      </div>
      <div class="stats-right">
        <label><%= @users.count %></label>        
      </div>
      <div class="clearfix"> </div> 
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3 ">
      <div class="stats-left">
        <h5>Total</h5>
        <h5>Requests</h5>
      </div>
      <div class="stats-right">
        <label> 0</label>
      </div>
      <div class="clearfix"> </div> 
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3 ">
      <div class="stats-left">
        <h5>Total Devices</h5>
        <h5>Fixed</h5>
      </div>
      <div class="stats-right">
        <label>0</label>
      </div>
      <div class="clearfix"> </div> 
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3 ">
      <div class="stats-left">
        <h5>Total</h5>
        <h5>Pending</h5>
      </div>
      <div class="stats-right">
        <label>0</label>
      </div>
      <div class="clearfix"> </div> 
    </div>
    <div class="clearfix"> </div> 
  </div>
</div>
</div>
<div class="graph-visual tables-main">
  <div class="ribbon-one graph">
        <div class="ribbon left_ribbon">
          <h3>Latest Bookings</h3>
          </div>
    <div class="graph">
        <div class="tables">        
          <table class="table table-hover"> 
            <thead>
             <tr>
              <th>#</th> <th>Firstname</th> <th>Lastnme</th> <th>Phone No</th><th>Address</th> <th>Status</th>
             </tr> 
            </thead> 
            <tbody>
              <% @users.each do |user| %>
             <tr> <th scope="row"><%= user.id %></th> <td><%= user.first_name.humanize %></td> <td><%= user.last_name.humanize %></td> <td><%= user.phone_number %></td><td>home address</td><td>Fixed</td> </tr> 
             <% end %>
              </tbody> 
           </table>
        </div>
    </div>
  </div>
      </div>


              

app/views/admins/invitations/edit.html.erb
 <% meta title: "Invited | Gofixam" %>

<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= simple_form_for resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <%= f.button :submit, t("devise.invitations.edit.submit_button") %>
<% end %>

<%= render 'shared/footer_scroll2'%>

app/views/admins/invitations/new.html.erb
 <% meta title: "Add Admin | Gofixam" %>

<div class="admin_wrapper">

		<div class="admin-header">
			<%=render 'bookings/navbar' %>
		</div>


		<div class="container">
<h2 class='form-inputs'><%= t "devise.invitations.new.header" %></h2>

<%= simple_form_for resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post} do |f| %>
  <div class="form-inputs">
  	<%if alert.present? || notice.present?%>
	  	<div class="alert alert-danger">
	  		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	  		<%= alert %> <%= notice %>
		</div>
	<%end%>


<% resource.class.invite_key_fields.each do |field| -%>
  <%= f.input field  %>
<% end -%>

<%= f.button :submit, t("devise.invitations.new.submit_button") ,class:'btn btn-primary'%>
<% end %>

</div>
</div>
</div>


<%=render "shared/footer_scroll2"%>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/admins/show.html.erb
<div class="container">
<nav  class="navbar navbar-inverse" role="navigation">
  
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">        
        <%= image_tag('GOFIX.png', class:'img-responsive', width:'400', height:'300')%>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "HOME" , home_index_path%></li>
      <li><%= link_to "ADD ADMIN", new_admin_invitation_path  %></li>
      <li>
      <li><%= link_to "FEEDBACKS", admins_path %></li>
      <li><%= form_tag admins_path, method: :get , remote:true do %>
            <p>
              <%= text_field_tag :search %>
              <%= submit_tag "Search" %>
            </p>
        <%end%>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to  destroy_admin_session_path do %>
              <span class="glyphicon glyphicon-log-out"></span>
               Logout(<%= current_admin.email%>)
          <%end%>
      </li>
    </ul>
    </div>
</nav>
<div class="row">
<div class="custom-widgets">
   <div class="row-one">
    <div class="col-sm-6 col-md-4 col-lg-3 ">
      
      <div class="stats-left ">
        <h5>Total</h5>
        <h5> Users</h5>
      </div>
      <div class="stats-right">
        <label><%= @users.count %></label>        
      </div>
      <div class="clearfix"> </div> 
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3 ">
      <div class="stats-left">
        <h5>Total</h5>
        <h5>Requests</h5>
      </div>
      <div class="stats-right">
        <label> 0</label>
      </div>
      <div class="clearfix"> </div> 
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3 ">
      <div class="stats-left">
        <h5>Total Devices</h5>
        <h5>Fixed</h5>
      </div>
      <div class="stats-right">
        <label>0</label>
      </div>
      <div class="clearfix"> </div> 
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3 ">
      <div class="stats-left">
        <h5>Total</h5>
        <h5>Pending</h5>
      </div>
      <div class="stats-right">
        <label>0</label>
      </div>
      <div class="clearfix"> </div> 
    </div>
    <div class="clearfix"> </div> 
  </div>
</div>
</div>
<div class="graph-visual tables-main">
  <div class="ribbon-one graph">
        <div class="ribbon left_ribbon">
          <h3>Latest Bookings</h3>
          </div>
    <div class="graph">
        <div class="tables">        
          <table class="table table-hover"> 
            <thead>
             <tr>
              <th>#</th> <th>Firstname</th> <th>Lastnme</th> <th>Phone No</th><th>Address</th> <th>Status</th>
             </tr> 
            </thead> 
            <tbody>
              <% @users.each do |user| %>
             <tr> <th scope="row"><%= user.id %></th> <td><%= user.first_name.humanize %></td> <td><%= user.last_name.humanize %></td> <td><%= user.phone_number %></td><td>home address</td><td>Fixed</td> </tr> 
             <% end %>
              </tbody> 
           </table>
        </div>
    </div>
  </div>
      </div>


              

app/views/dashboard/_body.html.erb
		<div class="table-responsive">
              <table class='table'>
              
                <thead>
                    <tr class="pitch_header">

                    <th>App Name</th>

                    <th>Pitched </th>

                    <th>Pitch Status </th>

                    <th>Action</th>

                    </tr>
                </thead>

                <tbody>
                <% @all_pitches.each do |pitch| %>

                <tr>

          			<td><div class="order_time"><%= pitch.company_name %></div>
                  </td>

                  <td><div class="order_time"><%= pitch.created_at.strftime("%d %b %Y") %>/<%= pitch.created_at.strftime('%H:%M %p')%></div>
                  </td>

                  <td> <div class="order_time"><%= pitch.pitch_status %></div>
                  </td>


                    <td>
                    <%=link_to edit_pitch_path(pitch), class:"btn btn-info"  do%>
                          <i class="glyphicon glyphicon-edit"></i> View Details
                    <% end -%>

                    <%=link_to pitch_path(pitch), class:"btn btn-danger",method: :delete,data: { confirm: "Are you sure?" }  do%>
                          <i class="glyphicon glyphicon-trash"></i> Delete
                    <% end -%>

                    </td>


                  </tr>


 <% end -%>

                </tbody>

               

                </table>
			
		</div>

app/views/dashboard/_navbar.html.erb
			<div class='admin-top'>
			 

			<%= form_tag dashboard_index_path, method: :get  do %>
				
					 <div class="input-group input-group-lg"> <%= text_field_tag :search,params[:search],class:"form-control",autocomplete:'off' %>
					<span class="input-group-btn"><%= submit_tag "Search",class:"btn btn-info" %></span>
					<%end%>
					</div>

			</div>
			 <nav class="navbar navbar-default adminnavbar">
					<div class="container-fluid">
					<div class="navbar-header">

				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar2">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>

			      <%=link_to  dashboard_index_path do  %>
					  <%=image_tag 'logo.PNG', class:"img-thumbnail  logoadmin" %>
					<%end%>
					
					

					</div>

				 <div class="collapse navbar-collapse" id="myNavbar2">
					<ul class="nav navbar-nav  navbar-right">

					<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">Pitch Menu
					<span class="caret"></span></a>
					<ul class="dropdown-menu">
					<li><%=link_to "All Pitches", all_dashboard_index_path %></li>
					<li><%=link_to "New Entries", pending_dashboard_index_path %></li>
					<li><%=link_to "Old Pitches", pitched_dashboard_index_path %></li>
					
					</ul>
					</li>

					<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">App Stats
					<span class="caret"></span></a>
					<ul class="dropdown-menu">
					<li><a href="dashboard/all">Total Pitches (<%=Pitch.all.count%>)</a></li>
					<li><a href="dashboard/pending">Pending Pitches (<%=Pitch.where("pitch_status='pending'").count%>)</a></li>
					<li><a href="dashboard/pitched">Old pitches (<%=Pitch.where("pitch_status='pitched'").count%>)</a></li>
					<li><a href="dashboard/pitched">No. of Admins (<%=Admin.count%>)</a></li>
					<li><a href="#">Subscribers (<%#Subscription.all.count%>)</a></li>
					
					</ul>
					</li>


					<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">Settings
					<span class="caret"></span></a>
					<ul class="dropdown-menu">
					<li><%# link_to "Add Admin", new_admin_invitation_path  %></li>
					<li><%= link_to "Add a Pitch", new_post_path  %></li>
					<li><%= link_to "Manage Pitch", post_index_path  %></li>
					<li>
					<%= link_to  destroy_admin_session_path,method: :delete  do %>
            Logout (<%= current_admin.email.split('@')[0] %>)
            <%end%>

					</li>
					
					</ul>
					</li>


					</ul>

					     

				</div>

					</div>
			</nav>

app/views/dashboard/all.html.erb

<% provide(:title, 'Admin Home | Gofixam')%>
<div class="admin_wrapper">

		<div class="admin-header">
			<%=render 'navbar' %>
		</div>



		<div class="container">  
  

   
<%=render 'body' %>


	
</div>

</div>


<%= render 'shared/footer2'%>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button> 

    <%=link_to  root_path do  %>
					  <%=image_tag 'logo.PNG', class:"img-thumbnail" %>   <% end -%>
  </div>

  <div class="navbar-collapse collapse">
	<ul class="nav navbar-nav navbar-right">
		<li class="dropdown">
			<a class="pitch_menu" href="/pitch/new"><span class="glyphicon glyphicon-user"></span> Pitch</a>
		</li>
		<li class="dropdown">
			<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-search menuicon"></span>
			</a>
			<ul class="dropdown-menu search-menu">
				<li>
					<%= form_tag home_index_path, method: :get  do %>
				
					 <div class="input-group input-group-sm">
					  <%= text_field_tag :search,params[:search],class:"form-control",autocomplete:'off',placeholder:'search category, startup, app, product, url' %>
					<span class="input-group-btn"><%= submit_tag "Search",class:"btn btn-info" %></span>

					</div>

					<%end%> 


				</li>
			</ul>
		</li>	
		<li class="dropdown">
			<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-list menuicon"></span><span class="caret">
			</a>

			<%=render 'home/menu_ul'%>










		</li>
	</ul>
  </div>
</nav>




app/views/pitch/new.html.erb
<div class="container-fluid">


<%= render 'shared/header'%>


<div class="container-fluid home_logo">
  <div class="container ">
  
  
<%= render 'home/navbar'%>
</div>
</div>


<div class="container-fluid pitch_new">

<div class="pitch_new2">
<div class="submit_a_startup">
	<h3>Tell us a little about you and your startup. </h3>
<h5></h5>
	</div>

<div class="pitch_content">
<%= form_for :pitch,url: pitch_index_path  do |f| %>

<p>
    <%= f.label :your_name %> <span class="required_pitch">*</span> <br>
    <%= f.text_field :owner_name,class:"form-control",autocomplete:"off",required:true %>
  </p>

<p>
    <%= f.label :email %> <span class="required_pitch">*</span> <br>
    <%= f.email_field :owner_email,class:"form-control",autocomplete:"off",required:true  %>
  </p>

    <p>
    <label>Company Address (If any)</label><br>
    <%= f.text_area :company_address,class:"form-control",autocomplete:"off"  %>
  </p>

  <p>
    <label>Contact phone <span class="required_pitch">*</span></label><br>
    <%= f.telephone_field :contact,class:"form-control",autocomplete:"off",required:true  %>
  </p>



  <p>
    <label> Startup Headline in one sentence</label> <span class="required_pitch">*</span> <br>
    <%= f.text_field :headline,class:"form-control",autocomplete:"off",required:true  %>
  </p>

 

  <p>
    <label>Product/Solution/Company Name <span class="required_pitch">*</span></label><br>
    <%= f.text_field :company_name,class:"form-control",autocomplete:"off",required:true  %>
  </p>

    <p>
    <label>Product/Solution/Company Category <span class="required_pitch">*</span></label><br>


      <%= f.select(:category, options_for_select([
         ['select category',''],
         ['Art & Design', 'Art & Design'],
         ['Auto & Vehicles', 'Auto & Vehicles'],
         ['Beauty', 'Beauty'],
         ['Books & Reference', 'Books & Reference'],
         ['Business', 'Business'],
         ['Comics', 'Comics'],
         ['Communications', 'Communications'],
         ['Education', 'Education'],
         ['Entertainment', 'Entertainment'],
         ['Events', 'Events'],
         ['Finance', 'Finance'],
         ['Food and Drink', 'Food and Drink'],
         ['Health & Fitness', 'Health & Fitness'],
         ['House & Home', 'House & Home'],
         ['Libraries & Demo', 'Libraries & Demo'],
         ['Lifestyle', 'Lifestyle'],
         ['Maps & Navigation', 'Maps & Navigation'],
         ['Medical', 'Medical'],
         ['Music & Audio', 'Music & Audio'],
         ['News & Magazines', 'News & Magazines'],
         ['Parenting', 'Parenting'],
         ['Personalization', 'Personalization'],
         ['Photography', 'Photography'],
         ['Productivity', 'Productivity'],
         ['Shopping', 'Shopping'],
         ['Social', 'Social'],
         ['Sports', 'Sports'],
         ['Travel & Local', 'Travel & Local'],
         ['Video Players & Editors', 'Video Players & Editors'],
         ['Weather', 'Weather']

    ]),:required => true, class: "form-control") %>


  </p>


  <p>
    <label>Describe your product, service or solution in more detail  <span class="required_pitch">*</span></label>
    <%= f.text_area :description,class:"form-control",autocomplete:"off",required:true  %>
  </p>

  

    <p>
    <label>Launch Date: <span class="required_pitch">*</span></label><br>
    <%= f.date_select :launch_date,class:"form-control",autocomplete:"off",required:true  %>
  </p>



  <p>
    <label>Product/App/Solution Link <span class="required_pitch">*</span></label><br>
    <%= f.text_field :app_link,class:"form-control",autocomplete:"off",required:true  %>
  </p>


   <p>
    <label>Team Members <span class="required_pitch">*</span></label><br>
    <%= f.text_field :team_members,class:"form-control",autocomplete:"off",required:true  %>
  </p>

   <p>
    <label>Anything else we need to know about your company or product?</label><br>
    <%= f.text_area :other_info,class:"form-control",autocomplete:"off"  %>
  </p>




 
  <p>
    <%= f.submit "Submit Startup",class:"btn btn-info" %>
  </p>

<% end %>
</div>



</div>




</div>







</div>
<%= render 'shared/footer'%>



app/views/post/_post_left.html.erb

<div class="row blog_main_div">

<div class="post_title2">

<%=link_to @post.title,post_path(@post.url),class:'post_url' %>

<div class="post_date">
 <%=@post.created_at.strftime('%B %d') %>, <%=@post.created_at.strftime('%Y') %>
</div>

<ul class="nav navbar-nav share">
		<li><div class="fb-share-button" data-href="http://www.gofixam.com/blog/<%=@post.url%>" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.gofixam.com%2Fblog%2F<%=@post.url%>&amp;src=sdkpreparse"></a></div></li>

		<li><div>
		<a class="twitter-share-button"
		href="http://www.gofixam.com/blog/<%=@post.url%>"
		data-size="large">
		Tweet</a>
		</div></li>

    </ul>

</div>



 <div class="col-sm-12">


  <%=image_tag @post.image  %>


<div class="showpost_content">
	<%= @post.post.html_safe %> 
 </div>


<div class="admin_auth_menu navbar-right">

<% if admin_signed_in? %>
	<%=link_to  edit_post_path(@post) do  %>
  <span class='glyphicon glyphicon-edit' title="Visible to admin only"></span>
<%end%>

<%=link_to  post_path(@post),method: :delete,data: { confirm: "Are you sure?" } do  %>

  <span class='glyphicon glyphicon-trash' title="Visible to admin only"></span>

<%end%>





<% end %>

</div>




 </div>

 </div>
                      

app/views/post/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/post/destroy.html.erb
<h1>Post#destroy</h1>
<p>Find me in app/views/post/destroy.html.erb</p>